services:
  - type: web
    name: inventario-restaurante
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: inventario-data
      mountPath: /opt/render/project/data
      sizeGB: 1
